mysql_db:    'asterisk'
mysql_host:  '127.0.0.1'
mysql_pass:  '***REMOVED***'
mysql_port:  '3306'
mysql_sock:  '/var/run/mysqld/mysqld.sock'
mysql_user:  'astrealtime'
rabbit_host: '127.0.0.1'
rabbit_pass: '***REMOVED***'
rabbit_user: 'wim'
redis_db:    '3'
redis_host:  '127.0.0.1'
redis_port:  '6379'
