---
  :output:
    User:
      :options:
        :fields:
          - id
          - name
          - email
          - fullname
          - zendesk_id
          - fullcontact
          - role_summary
          - skill_summary
          - language_summary
          - availability
          - visibility
          - activity
