---
  :output:
    User:
      :options:
        :fields:
          - id
          - email
          - name
          - fullcontact
          - last_sign_in_at
          - updated_at
          - role_summary
          - skill_summary
          - language_summary
          - availability
