development:
  sessions:
    default:
      database: voice_development
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: voice_test
      hosts:
        - localhost:27017
production:
  sessions:
    default:
      database: voice
      hosts:
        - localhost:27017
